In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split 
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import OneHotEncoder

In [65]:
# trasform the csv file to a dataframe 
df = pd.read_csv('C:/Users/ISHMO_CT/Desktop/projects/Loan_ML/Data/loan_data [Task 1-3] - loan_data.csv')

In [66]:
# print the first five rows of the data
df.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [67]:
# drop the Loan Id columns because it is unque throught so it won't help us in our model
# or we can make it an index 
df = df.set_index('Loan_ID')
df.head(3)

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
Loan_ID,,,,,,,,,,,,
LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y

In [68]:
# split the data into target and features 
target = 'Loan_Status'
y = df[target]
X = df.drop(columns=target)

In [69]:
# To esnure we have splitted our data the right way I print the shapes of target and features 
print(y.shape)
print(X.shape)

(614,)
(614, 11)

TASK 1


1a. Separate the data into training and test sets (use random_state=42 in the train_test_split for reproducibility).

In [70]:
# split the data into test and train set 
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [71]:
# print out the shapes to make sure I have splitted the datset right 
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(491, 11)
(491,)
(123, 11)
(123,)

1b. Create a model pipeline (for feature transformations)

In [72]:
# identify ordinal columns in features
ordinal_features = ['Dependents']
# define a transformation Pipeline for the ordinal features 
ordinal_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder()),
    ('scaler', StandardScaler())
])

In [73]:
# Identify categorical columns
categorical_columns = ['Gender', 'Married', 'Education', 'Self_Employed', 'Property_Area', ]
#define transformation pipeline for the categorical features
categorical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='constant', fill_value="MISSING")),
    ('ohe', OneHotEncoder(sparse_output=False, handle_unknown='ignore'))
])

In [74]:
# Identify numerical columns 
numerical_columns = ['Credit_History', 'Loan_Amount_Term', 'LoanAmount', 'CoapplicantIncome', 'ApplicantIncome']
# Define the tranformation pipeline for the numerical features
numerical_pipeline = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler)
])